
# Dockerfile.beat
FROM python:3.11

WORKDIR /app
ENV PYTHONPATH=/app


COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt


COPY . /app

CMD ["celery", "-A", "src.background.celery_app", "beat", "--loglevel=info"]

