version: "3.7"
services:
  wind_turbine_frontend:
    container_name: wind_turbine_frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - wind_turbine_frontend_network

networks:
  wind_turbine_frontend_network:
    driver: bridge
