FROM python:3.10.13-bookworm

WORKDIR /app

# Copy the requirements.txt first for better cache on later pushes
COPY ./requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

# Copy the main application
COPY . .

# Run the application
CMD ["python3", "src/store.py"]

